export const GET_BOOKS_LOADING = "GET_BOOKS_LOADING";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";

// export const GET_MORE_BOOKS_LOADING = "GET_MORE_BOOKS_LOADING";
// export const GET_MORE_BOOKS_SUCCESS = "GET_MORE_BOOKS_SUCCESS";
// export const GET_MORE_BOOKS_FAILURE = "GET_MORE_BOOKS_FAILURE";